"use client";
import "../globals.css";
import "../components/index.css";
import "../components/table.css";

interface BookingsData {
  id: number;
  name: string;
  event: string;
  ticketsSold?: number;
  ticketType: number;
  payment: number;
  status: string;
  venue: string;
}

const Bookings: BookingsData[] = [
  {
    id: 1,
    name: "Apolinary Theonest",
    event: "Festival A",
    ticketType: 1,
    payment: 3000,
    status: "PAID",
    venue: "Main Hall",
  },
  {
    id: 2,
    name: "Jane Doe",
    event: "Festival B",
    ticketType: 2,
    payment: 2000,
    status: "PENDING",
    venue: "Arena",
  },
  {
    id: 3,
    name: "Michael Okoye",
    event: "Concert X",
    ticketType: 3,
    payment: 4500,
    status: "PAID",
    venue: "Stadium",
  },
  {
    id: 4,
    name: "Sofia Mendes",
    event: "Tech Summit",
    ticketType: 1,
    payment: 5000,
    status: "CONFIRMED",
    venue: "Conference Center",
  },
  {
    id: 5,
    name: "Liam Chen",
    event: "Jazz Night",
    ticketType: 2,
    payment: 2500,
    status: "PENDING",
    venue: "Club Lounge",
  },
  {
    id: 6,
    name: "Aisha Khan",
    event: "Art Expo",
    ticketType: 1,
    payment: 1500,
    status: "PAID",
    venue: "Gallery Hall",
  },
  {
    id: 7,
    name: "Ravi Sharma",
    event: "Food Fest",
    ticketType: 3,
    payment: 3500,
    status: "CANCELLED",
    venue: "Open Park",
  },
  {
    id: 8,
    name: "Clara Novak",
    event: "Comedy Night",
    ticketType: 2,
    payment: 1800,
    status: "PAID",
    venue: "Theater",
  },
  {
    id: 9,
    name: "Zoe Mwamba",
    event: "Rock Concert",
    ticketType: 1,
    payment: 4000,
    status: "CONFIRMED",
    venue: "Arena",
  },
  {
    id: 10,
    name: "Tomas Rivera",
    event: "Film Premiere",
    ticketType: 2,
    payment: 3200,
    status: "PENDING",
    venue: "Cinema",
  },
  {
    id: 11,
    name: "Nia Brooks",
    event: "Dance Fest",
    ticketType: 3,
    payment: 2800,
    status: "PAID",
    venue: "Dance Hall",
  },
  {
    id: 12,
    name: "Samir Patel",
    event: "Startup Expo",
    ticketType: 1,
    payment: 6000,
    status: "CONFIRMED",
    venue: "Convention Center",
  },
  {
    id: 13,
    name: "Kira Sato",
    event: "Music Awards",
    ticketType: 2,
    payment: 7500,
    status: "PAID",
    venue: "Grand Arena",
  },
  {
    id: 14,
    name: "Devon Walsh",
    event: "Gaming Con",
    ticketType: 1,
    payment: 2200,
    status: "PENDING",
    venue: "Expo Hall",
  },
  {
    id: 15,
    name: "Fatima Ali",
    event: "Book Fair",
    ticketType: 3,
    payment: 1200,
    status: "PAID",
    venue: "Library Plaza",
  },
  {
    id: 16,
    name: "Jaden Park",
    event: "Fashion Show",
    ticketType: 2,
    payment: 5000,
    status: "CONFIRMED",
    venue: "Runway Hall",
  },
  {
    id: 17,
    name: "Amara Osei",
    event: "Cultural Fest",
    ticketType: 1,
    payment: 2000,
    status: "PAID",
    venue: "City Square",
  },
  {
    id: 18,
    name: "Luca Bianchi",
    event: "Science Expo",
    ticketType: 3,
    payment: 3000,
    status: "PENDING",
    venue: "Museum",
  },
  {
    id: 19,
    name: "Sofia Nguyen",
    event: "Wine Tasting",
    ticketType: 2,
    payment: 4500,
    status: "PAID",
    venue: "Vineyard",
  },
  {
    id: 20,
    name: "Omar Hassan",
    event: "Sports Gala",
    ticketType: 1,
    payment: 3500,
    status: "CONFIRMED",
    venue: "Stadium",
  },
  {
    id: 21,
    name: "Lila Gupta",
    event: "Theater Play",
    ticketType: 2,
    payment: 2800,
    status: "PAID",
    venue: "Main Theater",
  },
  {
    id: 22,
    name: "Elias Kim",
    event: "Charity Run",
    ticketType: 1,
    payment: 1000,
    status: "PENDING",
    venue: "City Park",
  },
  {
    id: 23,
    name: "Maya Lin",
    event: "Photography Expo",
    ticketType: 3,
    payment: 2500,
    status: "PAID",
    venue: "Art Gallery",
  },
  {
    id: 24,
    name: "Noah Silva",
    event: "Tech Conference",
    ticketType: 2,
    payment: 7000,
    status: "CONFIRMED",
    venue: "Tech Hub",
  },
  {
    id: 25,
    name: "Zara Ahmed",
    event: "Pop Concert",
    ticketType: 1,
    payment: 3800,
    status: "PAID",
    venue: "Arena",
  },
  {
    id: 26,
    name: "Isaac Moreno",
    event: "Food Truck Rally",
    ticketType: 3,
    payment: 1500,
    status: "PENDING",
    venue: "Downtown",
  },
  {
    id: 27,
    name: "Leila Santos",
    event: "Indie Film Fest",
    ticketType: 2,
    payment: 2000,
    status: "PAID",
    venue: "Cinema",
  },
  {
    id: 28,
    name: "Kai Zhang",
    event: "Art Workshop",
    ticketType: 1,
    payment: 1800,
    status: "CONFIRMED",
    venue: "Studio",
  },
  {
    id: 29,
    name: "Ava Torres",
    event: "Music Festival",
    ticketType: 3,
    payment: 5500,
    status: "PAID",
    venue: "Open Field",
  },
  {
    id: 30,
    name: "Rahul Desai",
    event: "Startup Pitch",
    ticketType: 2,
    payment: 4000,
    status: "PENDING",
    venue: "Innovation Hub",
  },
  {
    id: 31,
    name: "Esme Dubois",
    event: "Ballet Performance",
    ticketType: 1,
    payment: 3200,
    status: "PAID",
    venue: "Opera House",
  },
  {
    id: 32,
    name: "Yusuf Ibrahim",
    event: "Coding Bootcamp",
    ticketType: 3,
    payment: 6000,
    status: "CONFIRMED",
    venue: "Tech Center",
  },
  {
    id: 33,
    name: "Tara Lee",
    event: "Craft Fair",
    ticketType: 2,
    payment: 1200,
    status: "PAID",
    venue: "Market Square",
  },
  {
    id: 34,
    name: "Finn Doyle",
    event: "Gaming Tournament",
    ticketType: 1,
    payment: 2500,
    status: "PENDING",
    venue: "Esports Arena",
  },
  {
    id: 35,
    name: "Hana Kimura",
    event: "Sushi Workshop",
    ticketType: 2,
    payment: 2000,
    status: "PAID",
    venue: "Culinary School",
  },
  {
    id: 36,
    name: "Mateo Cruz",
    event: "Marathon",
    ticketType: 1,
    payment: 1500,
    status: "CONFIRMED",
    venue: "City Streets",
  },
  {
    id: 37,
    name: "Nadia Petrova",
    event: "Opera Night",
    ticketType: 3,
    payment: 5000,
    status: "PAID",
    venue: "Grand Theater",
  },
  {
    id: 38,
    name: "Arjun Mehta",
    event: "AI Summit",
    ticketType: 2,
    payment: 8000,
    status: "PENDING",
    venue: "Tech Park",
  },
  {
    id: 39,
    name: "Elena Ortiz",
    event: "Poetry Slam",
    ticketType: 1,
    payment: 1000,
    status: "PAID",
    venue: "Café",
  },
  {
    id: 40,
    name: "Malik Johnson",
    event: "Basketball Game",
    ticketType: 3,
    payment: 3000,
    status: "CONFIRMED",
    venue: "Sports Arena",
  },
  {
    id: 41,
    name: "Priya Rao",
    event: "Yoga Retreat",
    ticketType: 2,
    payment: 3500,
    status: "PAID",
    venue: "Resort",
  },
  {
    id: 42,
    name: "Theo Klein",
    event: "Car Show",
    ticketType: 1,
    payment: 2000,
    status: "PENDING",
    venue: "Exhibition Center",
  },
  {
    id: 43,
    name: "Anika Verma",
    event: "Dance Workshop",
    ticketType: 3,
    payment: 2500,
    status: "PAID",
    venue: "Studio",
  },
  {
    id: 44,
    name: "Hugo Lopes",
    event: "Tech Hackathon",
    ticketType: 2,
    payment: 4000,
    status: "CONFIRMED",
    venue: "Innovation Lab",
  },
  {
    id: 45,
    name: "Sana Malik",
    event: "Film Screening",
    ticketType: 1,
    payment: 1800,
    status: "PAID",
    venue: "Cinema",
  },
  {
    id: 46,
    name: "Evan Brooks",
    event: "Music Jam",
    ticketType: 3,
    payment: 3000,
    status: "PENDING",
    venue: "Club",
  },
  {
    id: 47,
    name: "Lina Costa",
    event: "Art Auction",
    ticketType: 2,
    payment: 5000,
    status: "PAID",
    venue: "Gallery",
  },
  {
    id: 48,
    name: "Rohan Patel",
    event: "Startup Summit",
    ticketType: 1,
    payment: 6500,
    status: "CONFIRMED",
    venue: "Convention Center",
  },
  {
    id: 49,
    name: "Mira Hassan",
    event: "Food Workshop",
    ticketType: 3,
    payment: 2200,
    status: "PAID",
    venue: "Kitchen Studio",
  },
  {
    id: 50,
    name: "Felix Wagner",
    event: "Classical Concert",
    ticketType: 2,
    payment: 4500,
    status: "PENDING",
    venue: "Concert Hall",
  },
];

export const BookingsTable = () => {
  return (
    <div className="table-wrapper">
      <h4>Recent Bookings</h4>
      <div className="table-container">
        <table className="custom-table">
          <thead>
            <tr>
            <th>Name</th>
              <th>Event</th>
              <th>Payment</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {Bookings.map((item) => (
              <tr key={item.id}>
                <td>{item.name}</td>
                <td>{item.event}</td>
                <td>Tzs. {item.payment || "-"}</td>
                <td>{item.status || "-"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
